# Generated by Django 3.0.8 on 2020-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0006_auto_20200707_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathtest',
            name='path',
            field=models.URLField(max_length=500),
        ),
    ]
