# Generated by Django 3.0.8 on 2020-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0008_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('image_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField(default=0)),
                ('Order_ID', models.IntegerField(default=0)),
                ('Products', models.IntegerField(default=0)),
                ('Month', models.DateTimeField()),
            ],
        ),
    ]
