# Generated by Django 3.0.8 on 2020-07-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0009_catalogue_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
