# Generated by Django 3.0.8 on 2020-07-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0010_auto_20200716_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='Products',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
