# Generated by Django 3.0.8 on 2020-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0011_auto_20200716_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='Products',
            field=models.TextField(max_length=100),
        ),
    ]
