# Generated by Django 3.0.8 on 2020-07-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0012_auto_20200716_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='Products',
            new_name='objectID',
        ),
    ]
