# Generated by Django 3.0.8 on 2020-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0013_auto_20200717_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='Order_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='Products',
            field=models.CharField(max_length=100),
        ),
    ]
