# Generated by Django 3.0.8 on 2020-07-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0014_auto_20200717_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='Order_ID',
        ),
    ]
