# Generated by Django 3.0.8 on 2020-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0015_remove_purchases_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='Products',
            field=models.CharField(max_length=20),
        ),
    ]
