# Generated by Django 3.0.8 on 2020-07-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0016_auto_20200717_0321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagetest',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
