# Generated by Django 3.0.8 on 2020-07-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0017_auto_20200717_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
